# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  push:
    branches: 
      - main
    tags:
      - 'v*'
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: (!startsWith(github.ref, 'refs/tags/'))
    name: Build Maui.XaleToolkit
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: dotnet restore ./src/Maui.XaleToolkit.sln
      
      - name: Build
        run: dotnet build --no-restore ./src/Maui.XaleToolkit.sln

  pack:
    if: startsWith(github.ref, 'refs/tags/')
    name: Pack Lib
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set NuGet version tag
        run: echo "NugetPackageVersion=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: 'Build Maui.XaleToolkit'
        run: dotnet pack ./src/Maui.XaleToolkit/Maui.XaleToolkit.csproj -c Release -p:PackageVersion=${{ env.NugetPackageVersion }} -p:Version=${{ env.NugetPackageVersion }}

      - name: Upload unsigned artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-packages
          path: ./packages/**/*.nupkg

  # sign:
  #   needs: [pack]
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: windows-latest
  #   name: Sign package

  #   steps:
  #     - name: Download unsigned artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: unsigned-packages
  #         path: ./packages

  #     - name: Install Signing Tool
  #       uses: actions/setup-dotnet@v4
  #       run: dotnet tool install --tool-path ./tools sign --version 0.9.1-beta.23356.1

  #     - name: Sign package
  #       run: >
  #         ./tools/sign code azure-key-vault
  #         **/*.nupkg
  #         --base-directory "${{ github.workspace }}/packages"
  #         --file-list "${{ github.workspace }}/SignClientFileList.txt"
  #         --publisher-name "axdelafuen"
  #         --description ".NET MAUI XaleToolkit"
  #         --description-url "https://github.com/axdelafuen/maui-xale-toolkit"
  #         --azure-key-vault-url "${{ secrets.SIGN_KEY_VAULT_URL }}"
  #         --azure-key-vault-client-id ${{ secrets.SIGN_CLIENT_ID }}
  #         --azure-key-vault-client-secret "${{ secrets.SIGN_CLIENT_SECRET }}"
  #         --azure-key-vault-tenant-id ${{ secrets.SIGN_TENANT_ID }}
  #         --azure-key-vault-certificate "${{ secrets.SIGN_CERTIFICATE }}"
  #         --verbosity Information

  #     - name: Upload package artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: signed-packages
  #         if-no-files-found: error
  #         path: |
  #           ${{ github.workspace }}/packages/**/*.nupkg

  push:
    needs: [pack]
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Install .NET SDK
        uses: actions/setup-dotnet@

      - name: Download artifact
        uses: actions/download-artifact@
        with:
          name: signed-packages
          path: ./packages

      - name: Push NuGet to GitHub
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.GIT_NUGET_API_KEY }} --source https://nuget.pkg.github.com/axdelafuen/index.json --skip-duplicate

#     - name: Push NuGet to NugetOrg
#       run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGETORG_NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
